package com.my.demo.wallet.entity;

import java.util.Date;

public class Coin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_coin.id
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_coin.name
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_coin.symbol
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_coin.contract
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    private String contract;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_coin.decimals
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    private Integer decimals;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_coin.confirmations
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    private Integer confirmations;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_coin.type
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_coin.status
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_coin.create_time
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_coin.modify_time
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_coin.id
     *
     * @return the value of wallet_coin.id
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_coin.id
     *
     * @param id the value for wallet_coin.id
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_coin.name
     *
     * @return the value of wallet_coin.name
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_coin.name
     *
     * @param name the value for wallet_coin.name
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_coin.symbol
     *
     * @return the value of wallet_coin.symbol
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_coin.symbol
     *
     * @param symbol the value for wallet_coin.symbol
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_coin.contract
     *
     * @return the value of wallet_coin.contract
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    public String getContract() {
        return contract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_coin.contract
     *
     * @param contract the value for wallet_coin.contract
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    public void setContract(String contract) {
        this.contract = contract == null ? null : contract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_coin.decimals
     *
     * @return the value of wallet_coin.decimals
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    public Integer getDecimals() {
        return decimals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_coin.decimals
     *
     * @param decimals the value for wallet_coin.decimals
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    public void setDecimals(Integer decimals) {
        this.decimals = decimals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_coin.confirmations
     *
     * @return the value of wallet_coin.confirmations
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    public Integer getConfirmations() {
        return confirmations;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_coin.confirmations
     *
     * @param confirmations the value for wallet_coin.confirmations
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    public void setConfirmations(Integer confirmations) {
        this.confirmations = confirmations;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_coin.type
     *
     * @return the value of wallet_coin.type
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_coin.type
     *
     * @param type the value for wallet_coin.type
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_coin.status
     *
     * @return the value of wallet_coin.status
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_coin.status
     *
     * @param status the value for wallet_coin.status
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_coin.create_time
     *
     * @return the value of wallet_coin.create_time
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_coin.create_time
     *
     * @param createTime the value for wallet_coin.create_time
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_coin.modify_time
     *
     * @return the value of wallet_coin.modify_time
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_coin.modify_time
     *
     * @param modifyTime the value for wallet_coin.modify_time
     *
     * @mbg.generated Wed Apr 24 17:12:42 CST 2019
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}