package com.my.demo.wallet.entity;

import java.util.Date;

public class Crypto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_crypto.id
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_crypto.address
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_crypto.keystore
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    private String keystore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_crypto.password
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_crypto.type
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_crypto.status
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_crypto.create_time
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_crypto.modify_time
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_crypto.id
     *
     * @return the value of wallet_crypto.id
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_crypto.id
     *
     * @param id the value for wallet_crypto.id
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_crypto.address
     *
     * @return the value of wallet_crypto.address
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_crypto.address
     *
     * @param address the value for wallet_crypto.address
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_crypto.keystore
     *
     * @return the value of wallet_crypto.keystore
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    public String getKeystore() {
        return keystore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_crypto.keystore
     *
     * @param keystore the value for wallet_crypto.keystore
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    public void setKeystore(String keystore) {
        this.keystore = keystore == null ? null : keystore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_crypto.password
     *
     * @return the value of wallet_crypto.password
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_crypto.password
     *
     * @param password the value for wallet_crypto.password
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_crypto.type
     *
     * @return the value of wallet_crypto.type
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_crypto.type
     *
     * @param type the value for wallet_crypto.type
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_crypto.status
     *
     * @return the value of wallet_crypto.status
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_crypto.status
     *
     * @param status the value for wallet_crypto.status
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_crypto.create_time
     *
     * @return the value of wallet_crypto.create_time
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_crypto.create_time
     *
     * @param createTime the value for wallet_crypto.create_time
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_crypto.modify_time
     *
     * @return the value of wallet_crypto.modify_time
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_crypto.modify_time
     *
     * @param modifyTime the value for wallet_crypto.modify_time
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}