package com.my.demo.wallet.mapper;

import com.my.demo.wallet.entity.Crypto;
import com.my.demo.wallet.entity.CryptoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CryptoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_crypto
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    long countByExample(CryptoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_crypto
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    int deleteByExample(CryptoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_crypto
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_crypto
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    int insert(Crypto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_crypto
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    int insertSelective(Crypto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_crypto
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    List<Crypto> selectByExample(CryptoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_crypto
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    Crypto selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_crypto
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    int updateByExampleSelective(@Param("record") Crypto record, @Param("example") CryptoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_crypto
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    int updateByExample(@Param("record") Crypto record, @Param("example") CryptoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_crypto
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    int updateByPrimaryKeySelective(Crypto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_crypto
     *
     * @mbg.generated Wed Apr 24 17:13:35 CST 2019
     */
    int updateByPrimaryKey(Crypto record);
}