package com.my.demo.wallet.mapper;

import com.my.demo.wallet.entity.Transaction;
import com.my.demo.wallet.entity.TransactionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_transaction
     *
     * @mbg.generated Wed Apr 24 17:11:50 CST 2019
     */
    long countByExample(TransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_transaction
     *
     * @mbg.generated Wed Apr 24 17:11:50 CST 2019
     */
    int deleteByExample(TransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_transaction
     *
     * @mbg.generated Wed Apr 24 17:11:50 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_transaction
     *
     * @mbg.generated Wed Apr 24 17:11:50 CST 2019
     */
    int insert(Transaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_transaction
     *
     * @mbg.generated Wed Apr 24 17:11:50 CST 2019
     */
    int insertSelective(Transaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_transaction
     *
     * @mbg.generated Wed Apr 24 17:11:50 CST 2019
     */
    List<Transaction> selectByExample(TransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_transaction
     *
     * @mbg.generated Wed Apr 24 17:11:50 CST 2019
     */
    Transaction selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_transaction
     *
     * @mbg.generated Wed Apr 24 17:11:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") Transaction record, @Param("example") TransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_transaction
     *
     * @mbg.generated Wed Apr 24 17:11:50 CST 2019
     */
    int updateByExample(@Param("record") Transaction record, @Param("example") TransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_transaction
     *
     * @mbg.generated Wed Apr 24 17:11:50 CST 2019
     */
    int updateByPrimaryKeySelective(Transaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_transaction
     *
     * @mbg.generated Wed Apr 24 17:11:50 CST 2019
     */
    int updateByPrimaryKey(Transaction record);
}